FROM golang:alpine

VOLUME [ "/go/src/webapi", "/usr/local/certs/", "/etc/letsencrypt/" ]

RUN apk --update add --no-cache build-base openssl certbot heirloom-mailx postfix

WORKDIR /go/src/webapi

EXPOSE [25, 6000]