FROM golang:alpine

VOLUME [ "/go/src/webapi", "/usr/local/certs/live/", "/etc/letsencrypt/live/" ]

RUN apk --update add --no-cache build-base openssl git heirloom-mailx postfix certbot

RUN go get github.com/taylor-vann/tvgtb/certificatesx

WORKDIR /go/src/webapi

EXPOSE [25, 6000]