FROM golang:alpine

VOLUME [ "/go/src/webapi", "/usr/local/certs/", "/etc/letsencrypt/live/" ]

RUN apk --update add --no-cache build-base openssl git certbot

WORKDIR /go/src/webapi

EXPOSE [3000, 3005]