FROM golang:alpine

VOLUME [ "/go/src/webapi", "/usr/local/certs/live/", "/etc/letsencrypt/live/" ]

RUN apk --update add --no-cache build-base openssl git certbot

RUN go get github.com/taylor-vann/tvgtb/certificatesx/

WORKDIR /go/src/webapi

EXPOSE [80, 443]