FROM golang:alpine

VOLUME [ "/go/src/webapi", "/usr/local/certs" ]
VOLUME [ "/usr/local/web_clients/web_client", "usr/local/web_clients/web_client_login" ]

RUN apk add --no-cache build-base git openssl

WORKDIR /go/src/webapi

EXPOSE 4000