# brian taylor vann
#

version: "3"
services:
  webapi:
    container_name: superdb_webapi_${http_port}
    build:
      context: ./webapi/
      dockerfile: dockerfile
    restart: always
    ports:
      - "${http_port}:80"
    volumes:
      - ./config/:/usr/local/config/
      - ./webapi/:/root/go/src/webapi/
    command: "go run /root/go/src/webapi/main.go"
  db:
    depends_on:
      - superdb_webapi_${http_port}
    container_name: superdb_pgsql_${pgsql_port}
    build:
      context: ./db_store/
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./db/data/:/data
      db_store:
        container_name: authn_db_store
        build:
          context: ./db_store/
          dockerfile: dockerfile
        restart: always
        env_file:
          - ./environment_variables.env
        volumes:
          - ./db_store/postgres_data/:/var/lib/postgresql/data/
        command: "-p 5100"