FROM alpine:latest

VOLUME [ \
  "/root/go/src/webapi/", \
  "/usr/local/certs/", \
  "/usr/local/config/" ]

RUN apk --update add --no-cache build-base git go

WORKDIR /root/go/src/webapi/

EXPOSE 80 443