FROM alpine:latest

VOLUME [ "/root/go/src/webapi/", "/usr/local/share/internal.briantaylorvann.com/" ]

RUN apk --update add --no-cache build-base curl git go nodejs npm

RUN npm install --global typescript

RUN go get \
  github.com/taylor-vann/weblog/toolbox/golang/infraclientx/fetchx/ \
  github.com/taylor-vann/weblog/toolbox/golang/infraclientx/sessionx/ \
  github.com/taylor-vann/weblog/toolbox/golang/infraclientx/verifyx/ \
  github.com/taylor-vann/weblog/toolbox/golang/jwtx/

WORKDIR /root/go/src/webapi

EXPOSE 80
