FROM alpine:latest

VOLUME [ "/go/src/webapi/", "/usr/local/share/briantaylorvann.com/" ]

RUN apk --update add --no-cache build-base git go nodejs-current npm

RUN go get \
  github.com/taylor-vann/weblog/toolbox/golang/infraclientx/fetchx/ \
  github.com/taylor-vann/weblog/toolbox/golang/infraclientx/sessionx/ \
  github.com/taylor-vann/weblog/toolbox/golang/infraclientx/verifyx/ \
  github.com/taylor-vann/weblog/toolbox/golang/jwtx/

WORKDIR /go/src/webapi

EXPOSE 80
