# Brian Taylor Vann
# taylorvann dot com

version: "3"
services:
  load-balancer:
    container_name: local-load-balancer
    build:
      context: ./nginx/
      dockerfile: nginx-dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/:ro
  authentication:
    container_name: authentication-web-api
    build:
      context: ./authentication/
      dockerfile: dockerfile.dev
    volumes:
      - ../authentication/web_api/:/usr/src/app/:ro
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
