# brian taylor vann
# briantaylorvann dot com

version: "3"
services:
  webapi:
    container_name: clients_webapi
    hostname: clients.briantaylorvann.com
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./environment_variables.env
    ports:
      - "3100:80"
    extra_hosts:
      - "authn.briantaylorvann.com:10.88.0.1"
      - "logs.briantaylorvann.com:10.88.0.1"
    volumes:
      - ./webapi/:/go/src/webapi/
      - ./webclients/:/var/briantaylorvann/
    command: "go run /go/src/webapi/main.go"
