FROM alpine:latest

VOLUME [ "/root/go/src/webapi/", "/usr/local/certs/live" ]

RUN apk --update add --no-cache build-base openssl git go certbot

RUN go get \
  golang.org/x/crypto/argon2/ \
  github.com/lib/pq/ \
  golang.org/x/net/publicsuffix/ \
  github.com/gomodule/redigo/redis/

WORKDIR /root/go/src/webapi/

EXPOSE 80