FROM golang:alpine

VOLUME [ "/go/src/webapi/", "/usr/local/certs/live" ]

RUN apk --update add --no-cache build-base openssl git certbot

RUN go get \
golang.org/x/crypto/argon2/ \
github.com/lib/pq/ \
golang.org/x/net/publicsuffix/ \
github.com/gomodule/redigo/redis/ \
github.com/taylor-vann/weblog/toolbox/golang/clientx/ \
github.com/taylor-vann/weblog/toolbox/golang/jwtx/ \
github.com/taylor-vann/weblog/toolbox/golang/verifyx/

WORKDIR /go/src/webapi

EXPOSE 80