FROM golang:alpine

VOLUME [ "/go/src/webapi/", "/usr/local/certs/" ]

RUN apk --update add --no-cache build-base openssl git

RUN go get github.com/lib/pq
RUN go get github.com/gomodule/redigo/redis
RUN go get golang.org/x/crypto/argon2

WORKDIR /go/src/webapi

EXPOSE 5000