# brian taylor vann
# taylorvann dot com

version: "3"
services:
  webapi:
    container_name: limiter_webapi
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "5040:443"
    volumes:
      - ./config/:/usr/local/config/
      - ./webapi/:/root/go/src/webapi/
    command: "go run /root/go/src/webapi/main.go"
  cache:
    depends_on:
      - limiter_webapi
    container_name: limiter_cache
    build:
      context: ./cache/
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./cache/data/:/data
