# brian taylor vann
# taylorvann dot com

# Use this docker-compose to create an authentication development server

# Reserved Ports:
# 5000  JSON Web Api
# 5100  Store Db
# 5200  Whitelist Cache
# 5205  Store Cache

version: "3"
services:
  webapi:
    container_name: authn_webapi
    hostname: authn.taylorvann.com
    build:
      context: ./webapi/
      dockerfile: dockerfile.dev
    depends_on:
      - authn_store_db
      - authn_store_cache
      - authn_whitelist_cache
    restart: always
    env_file:
      - ./environment_variables.dev.env
    ports:
      - "5000:5000"
    volumes:
      - ./webapi/:/go/src/webapi/
    command: "go run /go/src/webapi/main.go"
  store_db:
    container_name: authn_store_db
    build:
      context: ./store_db/
      dockerfile: dockerfile.dev
    restart: always
    env_file:
      - ./environment_variables.dev.env
    volumes:
      - ./store_db/postgres_data/:/var/lib/postgresql/data/
    command: "-p 5100"
  store_cache:
    container_name: authn_store_cache
    build:
      context: ./store_cache/
      dockerfile: dockerfile.dev
    restart: always
    volumes:
      - ./store_cache/redis_data/:/data
  whitelist_cache:
    container_name: authn_whitelist_cache
    build:
      context: ./whitelist_cache/
      dockerfile: dockerfile.dev
    restart: always
    volumes:
      - ./whitelist_cache/redis_data/:/data
