# brian taylor vann
# taylorvann dot com

version: "3"
services:
  webapi:
    container_name: authn_webapi
    depends_on:
      - authn_db_store
      - authn_cache_store
      - authn_cache_whitelist
    build:
      context: ./webapi/
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./environment_variables.env
    ports:
      - "3000:80"
    extra_hosts:
      - "authn.briantaylorvann.com:10.88.0.1" # IP should match docker / podman
      - "logs.briantaylorvann.com:10.88.0.1"  # IP should match docker / podman
    volumes:
      - ./webapi/:/go/src/webapi/
    command: "go run /go/src/webapi/main.go"
  db_store:
    container_name: authn_db_store
    build:
      context: ./db_store/
      dockerfile: dockerfile.dev
    restart: always
    env_file:
      - ./environment_variables.env
    volumes:
      - ./db_store/postgres_data/:/var/lib/postgresql/data/
    command: "-p 5100"
  cache_store:
    container_name: authn_cache_store
    build:
      context: ./cache_store/
      dockerfile: dockerfile.dev
    restart: always
    volumes:
      - ./cache_store/redis_data/:/data
  cache_whitelist:
    container_name: authn_cache_whitelist
    build:
      context: ./cache_whitelist/
      dockerfile: dockerfile.dev
    restart: always
    volumes:
      - ./cache_whitelist/redis_data/:/data