# brian taylor vann
# briantaylorvann dot com

version: "3"
services:
  webapi:
    container_name: blog_webapi
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./environment_variables.env
    ports:
      - "3050:80"
    volumes:
      - ./webapi/:/root/go/src/webapi/
    command: "go run /root/go/src/webapi/main.go"
