FROM python:3-alpine

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apk add --no-cache linux-headers g++

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

VOLUME [ "/usr/src/app" ]